version: '3.8'

services:
  couchdb:
    image: couchdb
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - ./dbdata:/opt/couchdb/data

  apache:
    build:
      context: ./apache
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - couchdb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - apache
